name: Cube Guardian Analysis

on:
  workflow_run:
    workflows: ["Cube Guardian ci workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-summary
          path: artifacts

      - name: Run Analysis Script
        run: |
          python src/cubeguardian_analyse.py
        working-directory: src
